<?php

namespace Lara;

// This constant is auto-generated by the build script.
// Manual modifications will be overwritten and may cause unexpected behavior.
const SDK_VERSION = "1.0.2";

class Version
{
    public static function get()
    {
        return SDK_VERSION;
    }
}